name: Datily Data Analysis # 1. the name of the Factory Line

on:
  push:                    # 2. Trigger: Runs every time you push code
  workflow_dispatch:       # 3. Trigger: Adds a manual "Run Now" button in Github UI

jobs:
  analyze-data:            # 4. The Name of the Job
    runs-on: ubuntu-latest # 5. The Worker: We are asking for a Linux machine

    steps:
      # Step A: The worker needs to download your code to its hard drive
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          python-version: '3.9'

      # Step C: install libraries from your requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step D: Run your actual analysis
      # Assumption: Your script saves a file named 'sales_plot.png'
      - name: Run Analysis Script
        run: python src/analysis.py

      # Step E: the "Magic" Step - Save the plot so you can see it!
      # If we don't do this, the worker deletes everything when it finishes.
      - name: Upload plot as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sales-report-plot
          path: sales_plot.png
